import { ROUTES } from './routes';

/**
 * Tool card definitions displayed on the Home page.
 * Each tool maps to a route, icon, color variant, category, badge, and description.
 */
export const TOOLS = [
  {
    title: 'Contador de caracteres',
    description: 'Cuenta caracteres, palabras y analiza tus textos de manera instantánea.',
    link: ROUTES.CHARACTER_COUNTER,
    icon: 'bi-textarea-t',
    color: 'blue',
    category: 'text',
    badge: 'Texto',
  },
  {
    title: 'Biblioteca de archivos',
    description: 'Encuentra y descarga archivos de prueba con diferentes extensiones y tamaños.',
    link: ROUTES.FILE_LIBRARY,
    icon: 'bi-folder',
    color: 'green',
    category: 'qa',
    badge: 'Pruebas QA',
  },
  {
    title: 'Encoder / Decoder',
    description: 'Codifica y decodifica texto en formatos Base64, URL y HTML fácilmente.',
    link: ROUTES.ENCODER,
    icon: 'bi-code-slash',
    color: 'red',
    category: 'text',
    badge: 'Codificación',
  },
  {
    title: 'Imagen → Base64',
    description: 'Convierte tus imágenes a cadenas Base64 y decodifica cadenas de vuelta a imágenes.',
    link: ROUTES.IMAGE_BASE64,
    icon: 'bi-image',
    color: 'orange',
    category: 'image',
    badge: 'Base64',
  },
  {
    title: 'Redimensionar imágenes',
    description: 'Redimensiona y ajusta las dimensiones de tus imágenes de forma rápida y sencilla.',
    link: ROUTES.IMAGE_RESIZER,
    icon: 'bi-aspect-ratio',
    color: 'green',
    category: 'image',
    badge: 'Edición',
  },
  {
    title: 'Convertidor de archivos',
    description: 'Convierte documentos de texto y hojas de cálculo de forma local y 100% segura.',
    link: ROUTES.FILE_CONVERTER,
    icon: 'bi-file-earmark-arrow-up',
    color: 'blue',
    category: 'converter',
    badge: 'Documentos',
  },
  {
    title: 'Convertidor de imágenes',
    description: 'Convierte imágenes entre PNG, JPG, WEBP, GIF, BMP e ICO de forma local en tu navegador.',
    link: ROUTES.IMAGE_CONVERTER,
    icon: 'bi-images',
    color: 'orange',
    category: 'converter',
    badge: 'Imágenes',
  },
  {
    title: 'Convertidor de video',
    description: 'Convierte videos a MP4 y WEBM de forma local directamente en tu navegador.',
    link: ROUTES.VIDEO_CONVERTER,
    icon: 'bi-film',
    color: 'red',
    category: 'converter',
    badge: 'Video',
  },
  {
    title: 'Convertidor de audio',
    description: 'Convierte muestras de audio a WAV, MP3, AAC, OGG y WEBM de forma local en tu navegador.',
    link: ROUTES.AUDIO_CONVERTER,
    icon: 'bi-music-note-beamed',
    color: 'green',
    category: 'converter',
    badge: 'Audio',
  },
  {
    title: 'Suite IA para QA (Gherkin/Matrix)',
    description: 'Genera escenarios Gherkin, matriz de pruebas y scripts Cypress/Playwright con IA.',
    link: ROUTES.HU_GHERKIN,
    icon: 'bi-robot',
    color: 'red',
    category: 'IA',
    badge: 'Inteligencia Artificial',
  },
  {
    title: 'Generador de Datos (QA Faker CO)',
    description: 'Genera NIT con DV (DIAN Colombia), Cédulas (CC/CE/TI), celulares (+57), tarjetas Luhn y JSON mock masivos.',
    link: ROUTES.MOCK_DATA,
    icon: 'bi-person-vcard',
    color: 'blue',
    category: 'qa',
    badge: 'Pruebas QA CO',
  },
  {
    title: 'Comparador Diff (Text & JSON)',
    description: 'Compara dos textos o estructuras JSON lado a lado e identifica diferencias de forma visual.',
    link: ROUTES.DIFF_CHECKER,
    icon: 'bi-file-diff',
    color: 'orange',
    category: 'text',
    badge: 'Utilidad',
  },
  {
    title: 'Decodificador e Inspector JWT',
    description: 'Inspecciona tokens JWT de forma local, analiza headers, payload y estado de expiración.',
    link: ROUTES.JWT_DECODER,
    icon: 'bi-key-fill',
    color: 'green',
    category: 'text',
    badge: 'Seguridad API',
  },
  {
    title: 'Convertidor de Datos (JSON/XML/YAML/CSV)',
    description: 'Convierte instantáneamente sets de datos entre formatos JSON, XML, YAML y CSV.',
    link: ROUTES.DATA_CONVERTER,
    icon: 'bi-arrow-left-right',
    color: 'blue',
    category: 'text',
    badge: 'Formatos',
  },
  {
    title: 'Evaluador Regex (Regex QA CO)',
    description: 'Prueba expresiones regulares en vivo con patrones para Colombia (NIT DIAN, Cédula, Celular, Placa) y universales.',
    link: ROUTES.REGEX_TESTER,
    icon: 'bi-regex',
    color: 'orange',
    category: 'text',
    badge: 'Validaciones CO',
  },

  {
    title: 'Contraste y Accesibilidad WCAG',
    description: 'Calcula el ratio de contraste entre texto y fondo para cumplir con normas WCAG 2.1.',
    link: ROUTES.CONTRAST_CHECKER,
    icon: 'bi-eye',
    color: 'green',
    category: 'image',
    badge: 'Accesibilidad',
  },
  {
    title: 'Simulador Responsive Multi-Pantalla',
    description: 'Simula cualquier URL en pantallas de smartphones, tablets y PCs con marcos realistas, rotación y vista paralela.',
    link: ROUTES.DEVICE_SIMULATOR,
    icon: 'bi-phone-landscape',
    color: 'blue',
    category: 'qa',
    badge: 'Responsive QA',
  },
];

