import { ROUTES } from './routes';

/**
 * Tool card definitions displayed on the Home page.
 * Each tool maps to a route, icon, color variant, category, badge, and description.
 */
export const TOOLS = [
  {
    title: 'Contador de caracteres',
    description: 'Cuenta caracteres, palabras y analiza tus textos de manera instantánea.',
    link: ROUTES.CHARACTER_COUNTER,
    icon: 'bi-textarea-t',
    color: 'blue',
    category: 'text',
    badge: 'Texto',
  },
  {
    title: 'Biblioteca de archivos',
    description: 'Encuentra y descarga archivos de prueba con diferentes extensiones y tamaños.',
    link: ROUTES.FILE_LIBRARY,
    icon: 'bi-folder',
    color: 'green',
    category: 'qa',
    badge: 'Pruebas QA',
  },
  {
    title: 'Encoder / Decoder',
    description: 'Codifica y decodifica texto en formatos Base64, URL y HTML fácilmente.',
    link: ROUTES.ENCODER,
    icon: 'bi-code-slash',
    color: 'red',
    category: 'text',
    badge: 'Codificación',
  },
  {
    title: 'Imagen → Base64',
    description: 'Convierte tus imágenes a cadenas Base64 y decodifica cadenas de vuelta a imágenes.',
    link: ROUTES.IMAGE_BASE64,
    icon: 'bi-image',
    color: 'orange',
    category: 'image',
    badge: 'Base64',
  },
  {
    title: 'Redimensionar imágenes',
    description: 'Redimensiona y ajusta las dimensiones de tus imágenes de forma rápida y sencilla.',
    link: ROUTES.IMAGE_RESIZER,
    icon: 'bi-aspect-ratio',
    color: 'green',
    category: 'image',
    badge: 'Edición',
  },
  {
    title: 'Convertidor de archivos',
    description: 'Convierte documentos de texto y hojas de cálculo de forma local y 100% segura.',
    link: ROUTES.FILE_CONVERTER,
    icon: 'bi-file-earmark-arrow-up',
    color: 'blue',
    category: 'converter',
    badge: 'Documentos',
  },
  {
    title: 'Convertidor de imágenes',
    description: 'Convierte imágenes entre PNG, JPG, WEBP, GIF, BMP e ICO de forma local en tu navegador.',
    link: ROUTES.IMAGE_CONVERTER,
    icon: 'bi-images',
    color: 'orange',
    category: 'converter',
    badge: 'Imágenes',
  },
  {
    title: 'Convertidor de video',
    description: 'Convierte videos a MP4 y WEBM de forma local directamente en tu navegador.',
    link: ROUTES.VIDEO_CONVERTER,
    icon: 'bi-film',
    color: 'red',
    category: 'converter',
    badge: 'Video',
  },
  {
    title: 'Convertidor de audio',
    description: 'Convierte muestras de audio a WAV, MP3, AAC, OGG y WEBM de forma local en tu navegador.',
    link: ROUTES.AUDIO_CONVERTER,
    icon: 'bi-music-note-beamed',
    color: 'green',
    category: 'converter',
    badge: 'Audio',
  },
    {
    title: 'Generador de casos Gherkin',
    description: 'Convierte tu HU en casos de prueba Gherkin funcionales utilizando Inteligencia Artifical.',
    link: ROUTES.HU_GHERKIN,
    icon: 'bi bi-opencollective',
    color: 'red',
    category: 'IA',
    badge: 'Inteligencia Artificial',
  },
];
